# Generated by Django 5.2.15 on 2026-06-19 21:16

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SupportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body_id', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('gallery', 3), ('quote', 6), ('callout', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Sub-judul'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Paragraf'}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'icon': 'image', 'label': 'Galeri'}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('attribution', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 9: ('wagtail.blocks.StructBlock', [[('heading', 7), ('body', 8)]], {})})),
                ('body_en', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('gallery', 3), ('quote', 6), ('callout', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Sub-judul'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Paragraf'}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'icon': 'image', 'label': 'Galeri'}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('attribution', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 9: ('wagtail.blocks.StructBlock', [[('heading', 7), ('body', 8)]], {})})),
                ('account_holder', models.CharField(blank=True, max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=255)),
                ('swift_code', models.CharField(blank=True, max_length=255)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body_id', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('gallery', 3), ('quote', 6), ('callout', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Sub-judul'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Paragraf'}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'icon': 'image', 'label': 'Galeri'}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('attribution', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 9: ('wagtail.blocks.StructBlock', [[('heading', 7), ('body', 8)]], {})})),
                ('body_en', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('gallery', 3), ('quote', 6), ('callout', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Sub-judul'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Paragraf'}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'icon': 'image', 'label': 'Galeri'}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('attribution', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 9: ('wagtail.blocks.StructBlock', [[('heading', 7), ('body', 8)]], {})})),
                ('intro_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('excerpt', models.TextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('gallery', 3), ('quote', 6), ('callout', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Sub-judul'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Paragraf'}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'icon': 'image', 'label': 'Galeri'}), 4: ('wagtail.blocks.TextBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 4), ('attribution', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 9: ('wagtail.blocks.StructBlock', [[('heading', 7), ('body', 8)]], {})})),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_heading', models.CharField(blank=True, max_length=255)),
                ('hero_subheading_id', models.TextField(blank=True)),
                ('hero_subheading_en', models.TextField(blank=True)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('support_cta_text', models.CharField(blank=True, max_length=255)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='core.supportpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
