# Generated by Django 5.2.15 on 2026-06-21 00:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_homepage_hero_image_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='body_en',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('gallery', 4), ('quote', 7), ('callout', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Sub-judul', 'template': 'core/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Paragraf', 'template': 'core/blocks/paragraph_block.html'}), 2: ('wagtail.images.blocks.ImageBlock', [], {'template': 'core/blocks/image_block.html'}), 3: ('wagtail.images.blocks.ImageBlock', [], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'icon': 'image', 'label': 'Galeri', 'template': 'core/blocks/gallery_block.html'}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('text', 5), ('attribution', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 10: ('wagtail.blocks.StructBlock', [[('heading', 8), ('body', 9)]], {})}),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='body_id',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('gallery', 4), ('quote', 7), ('callout', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Sub-judul', 'template': 'core/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Paragraf', 'template': 'core/blocks/paragraph_block.html'}), 2: ('wagtail.images.blocks.ImageBlock', [], {'template': 'core/blocks/image_block.html'}), 3: ('wagtail.images.blocks.ImageBlock', [], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'icon': 'image', 'label': 'Galeri', 'template': 'core/blocks/gallery_block.html'}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('text', 5), ('attribution', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 10: ('wagtail.blocks.StructBlock', [[('heading', 8), ('body', 9)]], {})}),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('gallery', 4), ('quote', 7), ('callout', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Sub-judul', 'template': 'core/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Paragraf', 'template': 'core/blocks/paragraph_block.html'}), 2: ('wagtail.images.blocks.ImageBlock', [], {'template': 'core/blocks/image_block.html'}), 3: ('wagtail.images.blocks.ImageBlock', [], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'icon': 'image', 'label': 'Galeri', 'template': 'core/blocks/gallery_block.html'}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('text', 5), ('attribution', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 10: ('wagtail.blocks.StructBlock', [[('heading', 8), ('body', 9)]], {})}),
        ),
        migrations.AlterField(
            model_name='supportpage',
            name='body_en',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('gallery', 4), ('quote', 7), ('callout', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Sub-judul', 'template': 'core/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Paragraf', 'template': 'core/blocks/paragraph_block.html'}), 2: ('wagtail.images.blocks.ImageBlock', [], {'template': 'core/blocks/image_block.html'}), 3: ('wagtail.images.blocks.ImageBlock', [], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'icon': 'image', 'label': 'Galeri', 'template': 'core/blocks/gallery_block.html'}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('text', 5), ('attribution', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 10: ('wagtail.blocks.StructBlock', [[('heading', 8), ('body', 9)]], {})}),
        ),
        migrations.AlterField(
            model_name='supportpage',
            name='body_id',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('gallery', 4), ('quote', 7), ('callout', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'title', 'label': 'Sub-judul', 'template': 'core/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'icon': 'pilcrow', 'label': 'Paragraf', 'template': 'core/blocks/paragraph_block.html'}), 2: ('wagtail.images.blocks.ImageBlock', [], {'template': 'core/blocks/image_block.html'}), 3: ('wagtail.images.blocks.ImageBlock', [], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'icon': 'image', 'label': 'Galeri', 'template': 'core/blocks/gallery_block.html'}), 5: ('wagtail.blocks.TextBlock', (), {}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('text', 5), ('attribution', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 10: ('wagtail.blocks.StructBlock', [[('heading', 8), ('body', 9)]], {})}),
        ),
    ]
