# Generated by Django 5.2.15 on 2026-06-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hero_heading_bilingual'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='blogger_post_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
